In [1]:
import pandas as pd
import numpy as np

In [2]:
# ładowanie danych
portfolio = pd.read_csv('przykladowe_portfolio.txt', sep=';')
wskazniki = pd.read_csv('przykladowe_wskazniki.txt', sep=';')
# usuwam jedną niepotrzebną kolumnę która mi się zrobiła przypadkowo przy tworzeniu przykładowych danych
wskazniki.drop('Unnamed: 2', inplace=True, axis=1)

In [3]:
portfolio

nazwa  liczba_akcji  obecny_kurs
0               Adobe             2         35.0
1              Makita             3         17.0
2   21 st Century Fox             4         23.0
3           Starbucks             5         12.0
4            Facebook             7         30.0
5          BlackBerry             2         55.0
6                EBay            12         11.0
7             Netflix            15          9.0
8             Moderna             3         34.0
9         AstraZeneca             5         14.0
10              Apple             4         46.0
11             NASDAQ             1        130.0
12             Garmin            29          6.0

In [4]:
# liczę wartość posiadanych akcji każdej firmy
portfolio['wartosc'] = portfolio['liczba_akcji'] * portfolio['obecny_kurs']
# zsumowana wartość całego portfolio przy obecnym kursie 
portfolio_value = portfolio['wartosc'].sum()
print('portfolio_value', portfolio_value)
# procent wartości akcji w stosunku do wartości całego portfolio
portfolio['procent_wartosci'] = portfolio['wartosc'] / portfolio_value

portfolio_value 1520.0


In [5]:
portfolio

nazwa  liczba_akcji  obecny_kurs  wartosc  procent_wartosci
0               Adobe             2         35.0     70.0          0.046053
1              Makita             3         17.0     51.0          0.033553
2   21 st Century Fox             4         23.0     92.0          0.060526
3           Starbucks             5         12.0     60.0          0.039474
4            Facebook             7         30.0    210.0          0.138158
5          BlackBerry             2         55.0    110.0          0.072368
6                EBay            12         11.0    132.0          0.086842
7             Netflix            15          9.0    135.0          0.088816
8             Moderna             3         34.0    102.0          0.067105
9         AstraZeneca             5         14.0     70.0          0.046053
10              Apple             4         46.0    184.0          0.121053
11             NASDAQ             1        130.0    130.0          0.085526
12             Garmin            29          6.0    174.0          0.114474

In [6]:
wskazniki

sredni_zysk  srednie_odchylenie
0         0.534               5.465
1        -1.749               6.544
2         1.837               7.734
3         0.352               6.283
4         0.163               8.365
5         0.857               4.869
6        -0.874               2.134
7        -0.632               6.674
8         1.375               5.872
9         0.386               3.985
10       -1.474               7.862
11        0.284               4.236
12        1.347               8.357

In [7]:
# łączenie tabeli portfolio z tabelą wskaźniki
portfolio = portfolio.join(wskazniki)
portfolio

nazwa  liczba_akcji  obecny_kurs  wartosc  procent_wartosci  \
0               Adobe             2         35.0     70.0          0.046053   
1              Makita             3         17.0     51.0          0.033553   
2   21 st Century Fox             4         23.0     92.0          0.060526   
3           Starbucks             5         12.0     60.0          0.039474   
4            Facebook             7         30.0    210.0          0.138158   
5          BlackBerry             2         55.0    110.0          0.072368   
6                EBay            12         11.0    132.0          0.086842   
7             Netflix            15          9.0    135.0          0.088816   
8             Moderna             3         34.0    102.0          0.067105   
9         AstraZeneca             5         14.0     70.0          0.046053   
10              Apple             4         46.0    184.0          0.121053   
11             NASDAQ             1        130.0    130.0          0.085526   
12             Garmin            29          6.0    174.0          0.114474   

    sredni_zysk  srednie_odchylenie  
0         0.534               5.465  
1        -1.749               6.544  
2         1.837               7.734  
3         0.352               6.283  
4         0.163               8.365  
5         0.857               4.869  
6        -0.874               2.134  
7        -0.632               6.674  
8         1.375               5.872  
9         0.386               3.985  
10       -1.474               7.862  
11        0.284               4.236  
12        1.347               8.357

In [8]:
# licze sharpe ratio
portfolio['sharpe_ratio'] = portfolio['sredni_zysk'] / portfolio['srednie_odchylenie']
portfolio
# średni zysk = expected return w filmiku
# średnie odchylenie = standard deviation w filmiku
# sharpe ratio to tak samo

nazwa  liczba_akcji  obecny_kurs  wartosc  procent_wartosci  \
0               Adobe             2         35.0     70.0          0.046053   
1              Makita             3         17.0     51.0          0.033553   
2   21 st Century Fox             4         23.0     92.0          0.060526   
3           Starbucks             5         12.0     60.0          0.039474   
4            Facebook             7         30.0    210.0          0.138158   
5          BlackBerry             2         55.0    110.0          0.072368   
6                EBay            12         11.0    132.0          0.086842   
7             Netflix            15          9.0    135.0          0.088816   
8             Moderna             3         34.0    102.0          0.067105   
9         AstraZeneca             5         14.0     70.0          0.046053   
10              Apple             4         46.0    184.0          0.121053   
11             NASDAQ             1        130.0    130.0          0.085526   
12             Garmin            29          6.0    174.0          0.114474   

    sredni_zysk  srednie_odchylenie  sharpe_ratio  
0         0.534               5.465      0.097713  
1        -1.749               6.544     -0.267268  
2         1.837               7.734      0.237523  
3         0.352               6.283      0.056024  
4         0.163               8.365      0.019486  
5         0.857               4.869      0.176012  
6        -0.874               2.134     -0.409560  
7        -0.632               6.674     -0.094696  
8         1.375               5.872      0.234162  
9         0.386               3.985      0.096863  
10       -1.474               7.862     -0.187484  
11        0.284               4.236      0.067044  
12        1.347               8.357      0.161182

In [9]:
# losuję przykładową macierz waiancji-kowariancji
covariance_matrix = 0.008 * np.random.rand(13,13) - 0.003
covariance_matrix

array([[ 2.27985198e-03, -1.00328631e-03,  4.53737393e-03,
         4.27059244e-03,  2.73560000e-03, -4.80373860e-04,
        -2.39673059e-03, -1.94956120e-04,  4.33826214e-03,
        -2.85941465e-04,  6.04158617e-04,  2.17944967e-03,
         2.32226641e-03],
       [ 4.40279229e-03, -1.35627445e-03,  4.79472438e-03,
        -2.56333429e-03, -1.02673569e-03,  1.09458255e-03,
         5.17305830e-04, -1.55445111e-03,  3.54453979e-03,
         3.50684260e-03,  1.77649903e-03,  3.50117638e-03,
         1.12116585e-03],
       [-3.73244828e-05, -1.85847904e-03,  1.01919020e-03,
         3.62573270e-03,  3.17833410e-03,  4.08181582e-03,
        -7.23269776e-04, -2.22808241e-03, -2.42542189e-03,
         3.61648306e-03,  3.18265232e-03, -5.56276524e-04,
         3.13462870e-04],
       [-1.43580129e-03,  2.57854211e-04, -2.27782206e-04,
         8.98546188e-04, -2.07482944e-03, -1.88408881e-03,
        -2.97803268e-03, -2.10025332e-03,  3.66773915e-03,
        -2.05933800e-03,  2.26864668e

In [10]:
# oczekiwany zwrot z portfolio
portfolio_exp_return = (portfolio['sredni_zysk'] * portfolio['procent_wartosci']).sum()
portfolio_exp_return

0.15359802631578942

In [11]:
# zamieniam pandasową kolumnę na format akceptowany przez numpy
weights = portfolio['procent_wartosci'].to_numpy()

In [12]:
# odchylenie standardowe portfolio
portfolio_std_deviation = np.sqrt(np.matmul(np.matmul(weights, covariance_matrix), weights))
portfolio_std_deviation

0.0324176407518595

In [13]:
# sharpe ratio dla całego portfolio
portfolio_sharpe_ratio = portfolio_exp_return / portfolio_std_deviation
portfolio_sharpe_ratio

4.738100082344176

# Test dla danych (prawie takich samych) jak w filmiku na yt

In [44]:
portfolio = pd.read_csv('film_portfolio.txt')
portfolio

name  exp_ret  std_dev  weights
0  SPY -0.00033  0.05465    0.125
1  MDY  0.00235  0.06544    0.125
2  SLY  0.00228  0.07204    0.125
3  EFA -0.00439  0.06946    0.125
4  EEM  0.00124  0.08707    0.125
5  TLT  0.00818  0.04594    0.125
6  LQD  0.00539  0.02858    0.125
7  GLD  0.01462  0.06016    0.125

In [45]:
# licze sharpe ratio
# to jest tabelka dokładnie taka jak w filmie
portfolio['sharpe_ratio'] = portfolio['exp_ret'] / portfolio['std_dev']
portfolio

name  exp_ret  std_dev  weights  sharpe_ratio
0  SPY -0.00033  0.05465    0.125     -0.006038
1  MDY  0.00235  0.06544    0.125      0.035911
2  SLY  0.00228  0.07204    0.125      0.031649
3  EFA -0.00439  0.06946    0.125     -0.063202
4  EEM  0.00124  0.08707    0.125      0.014241
5  TLT  0.00818  0.04594    0.125      0.178058
6  LQD  0.00539  0.02858    0.125      0.188593
7  GLD  0.01462  0.06016    0.125      0.243019

In [46]:
# 3 wartości których potrzebuję potem w solverze
maximum_expected_return = max(portfolio['exp_ret'])
maximum_expected_return

0.01462

In [47]:
minimum_standard_deviation = min(portfolio['std_dev'])
minimum_standard_deviation

0.02858

In [48]:
maximum_sharpe_ratio = max(portfolio['sharpe_ratio'])
maximum_sharpe_ratio

0.24301861702127658

In [49]:
# macierz kowariancji taka jak w filmiku
# tak, przepisywałam to wszystko XD
covariance_matrix = pd.read_csv('film_kowariancja.txt', names=['SPY','MDY','SLY','EFA','EEM','TLT','LQD','GLD'])
covariance_matrix

SPY       MDY       SLY       EFA       EEM       TLT       LQD  \
0  0.002987  0.003433  0.003759  0.003552  0.004195 -0.000690  0.000566   
1  0.003433  0.004282  0.004645  0.004051  0.005018 -0.000980  0.000624   
2  0.003759  0.004645  0.005190  0.004387  0.005371 -0.001040  0.000662   
3  0.003552  0.004051  0.004387  0.004824  0.005585 -0.000570  0.000899   
4  0.004195  0.005018  0.005371  0.005585  0.007582 -0.001080  0.000921   
5 -0.000690 -0.000980 -0.001040 -0.000570 -0.001080  0.002111  0.000516   
6  0.000566  0.000624  0.000662  0.000899  0.000921  0.000516  0.000817   
7  0.000345  0.000498  0.000352  0.000767  0.001528  0.000425  0.000291   

        GLD  
0  0.000345  
1  0.000498  
2  0.000352  
3  0.000767  
4  0.001528  
5  0.000425  
6  0.000291  
7  0.003619

In [50]:
# zmieniam se tylko format tej tabelki na brzydszy nampajowy
covariance_matrix = covariance_matrix.to_numpy()
covariance_matrix

array([[ 0.002987,  0.003433,  0.003759,  0.003552,  0.004195, -0.00069 ,
         0.000566,  0.000345],
       [ 0.003433,  0.004282,  0.004645,  0.004051,  0.005018, -0.00098 ,
         0.000624,  0.000498],
       [ 0.003759,  0.004645,  0.00519 ,  0.004387,  0.005371, -0.00104 ,
         0.000662,  0.000352],
       [ 0.003552,  0.004051,  0.004387,  0.004824,  0.005585, -0.00057 ,
         0.000899,  0.000767],
       [ 0.004195,  0.005018,  0.005371,  0.005585,  0.007582, -0.00108 ,
         0.000921,  0.001528],
       [-0.00069 , -0.00098 , -0.00104 , -0.00057 , -0.00108 ,  0.002111,
         0.000516,  0.000425],
       [ 0.000566,  0.000624,  0.000662,  0.000899,  0.000921,  0.000516,
         0.000817,  0.000291],
       [ 0.000345,  0.000498,  0.000352,  0.000767,  0.001528,  0.000425,
         0.000291,  0.003619]])

In [51]:
# kolumnę weights też potrzebuję w formacie numpy żeby policzyć reszte rzeczy
weights = portfolio['weights'].to_numpy()
weights

array([0.125, 0.125, 0.125, 0.125, 0.125, 0.125, 0.125, 0.125])

#### w tych 3 komórkach poniżej sprawdzam tylko czy dobrze liczę, odpowiednie funkcje do liczenia tych rzeczy są niżej

In [52]:
# oczekiwany zwrot z portfolio
portfolio_exp_return = np.matmul(portfolio['exp_ret'], portfolio['weights'])
portfolio_exp_return

0.0036674999999999998

In [53]:
# odchylenie standardowe portfolio
portfolio_std_deviation = np.sqrt(np.matmul(np.matmul(weights, covariance_matrix), weights))
portfolio_std_deviation

0.04462902642899574

In [54]:
# sharpe ratio dla całego portfolio
portfolio_sharpe_ratio = portfolio_exp_return / portfolio_std_deviation
portfolio_sharpe_ratio

0.08217745923350915

### okej, wszystko do tego momentu śmiga jak trzeba

In [55]:
import scipy.optimize as opt

In [56]:
# funkcja która liczy na raz odchylenie standardowe portfolio w zależności od wag
# covariance_matrix musi być zmienną globalną
def get_portfolio_std_deviation(weights):
    portfolio_std_deviation = np.sqrt(np.matmul(np.matmul(weights, covariance_matrix), weights))
    return portfolio_std_deviation

In [57]:
get_portfolio_std_deviation(weights)

0.04462902642899574

In [58]:
exp_returns = portfolio['exp_ret'].to_numpy()

In [59]:
# funkcja która liczy na raz oczekiwany zwrot z portfolio w zależności od wag
# exp_returns musi być zmienną globalną
def get_portfolio_exp_return(weights):
    portfolio_exp_return = np.matmul(exp_returns, weights)
    return portfolio_exp_return

In [60]:
get_portfolio_exp_return(weights)

0.0036674999999999998

In [61]:
# funkcja która liczy na raz sharpe ratio całego portfolio w zależności od wag
# covariance_matrix musi być zmienną globalną
def get_portfolio_sharpe_ratio(weights):
    portfolio_sharpe_ratio = np.matmul(exp_returns, weights) / np.sqrt(np.matmul(np.matmul(weights, covariance_matrix), weights))
    return portfolio_sharpe_ratio

In [62]:
get_portfolio_sharpe_ratio(weights)

0.08217745923350915

### Optymalizacja z 2 kolumny (nazwanej w filmiku Max Ret):
##### maksymalizuję expected return przy utrzymaniu najniższego standard deviation jakie było w portfolio

In [63]:
# ograniczenie, że liczba akcji
# (dokładniej wagi czyli stosunek wartości akcji względem wartości całego portfolio) 
# nie może być ujemna
# to ograniczenie stosuję we wszystkich 3 typach optymalizacji
bnds = ((0, None), (0, None), (0, None), (0, None), (0, None), (0, None), (0, None), (0, None))

In [64]:
# ograniczenie, że wszytskie wagi razem wzięte muszą wynosić 1 (100%)
# ograniczenie że portfolio std deviation ma pozostać nie większe, niż było w portfolio
# get_portfolio_std_deviation <= minimum_standard_deviation
# minimum_standard_deviation - get_portfolio_std_deviation >= 0

cons = ({'type': 'eq', 'fun': lambda x:  sum(x) - 1},
        {'type': 'ineq', 'fun': lambda x: minimum_standard_deviation - get_portfolio_std_deviation(x)})

In [ ]:
result = opt.minimize(get_portfolio_exp_return, weights, bounds=bnds, constraints=cons)
result

### Optymalizacja z 3 kolumny (nazwanej w filmiku Min St Dev):
##### minimalizuję std deviation przy utrzymaniu największego expected return jakie było w portfolio

In [65]:
# ograniczenie, że wszytskie wagi razem wzięte muszą wynosić 1 (100%)
# ograniczenie że portfolio expected return ma pozostać nie mniejsze, niż było w portfolio
# get_portfolio_exp_return >= maximum_expected_return
# get_portfolio_exp_return - maximum_expected_return >= 0

cons = ({'type': 'eq', 'fun': lambda x:  sum(x) - 1},
        {'type': 'ineq', 'fun': lambda x: get_portfolio_exp_return(x) - maximum_expected_return})

In [69]:
# tutaj działa solver i z ważnych rzeczy wypluwa:
# fun: to jest najlepszy wynik funkcji jaki się udało uzyskać, w tym przypadku minimalne std deviation
# x: to są wagi dające minimalne std deviation, to jest najważniejsza rzecz u nas
#    (mówi co użytkownik ma pozmieniać, żeby uzyskać najlepsze wyniki)
result = opt.minimize(get_portfolio_std_deviation, weights, constraints=cons)
result

     fun: 0.03160353805956241
     jac: array([-0.00033831,  0.0054703 ,  0.00524215, -0.0090188 ,  0.00309087,
        0.0178373 ,  0.01183114,  0.03154177])
 message: 'Optimization terminated successfully'
    nfev: 270
     nit: 30
    njev: 30
  status: 0
 success: True
       x: array([ 0.41892481,  0.25630426,  0.14996734, -1.12117757,  0.24361838,
        0.22786209,  0.57726585,  0.24723485])

In [70]:
# tak się uzyskuje same wagi, żeby potem je gdzieś przekazać czy wyświetlić
result.x

array([ 0.41892481,  0.25630426,  0.14996734, -1.12117757,  0.24361838,
        0.22786209,  0.57726585,  0.24723485])

In [71]:
# a tak wynik
result.fun

0.03160353805956241

In [68]:
# można se też sprawdzić czy wagi fajnie sumują się do 1 (100%)
sum(result.x)

1.0

### Optymalizacja z 4 kolumny (nazwanej w filmiku Max SR):
##### maksymalizuję sharpe ratio przy utrzymaniu największego expected return i najmniejszego std deviation jakie było w portfolio