In [12]:
import pandas as pd
import numpy as np

In [13]:
# ładowanie danych
portfolio = pd.read_csv('przykladowe_portfolio.txt', sep=';')
wskazniki = pd.read_csv('przykladowe_wskazniki.txt', sep=';')
# usuwam jedną niepotrzebną kolumnę która mi się zrobiła przypadkowo przy tworzeniu przykładowych danych
wskazniki.drop('Unnamed: 2', inplace=True, axis=1)

In [14]:
portfolio

nazwa  liczba_akcji  obecny_kurs
0               Adobe             2         35.0
1              Makita             3         17.0
2   21 st Century Fox             4         23.0
3           Starbucks             5         12.0
4            Facebook             7         30.0
5          BlackBerry             2         55.0
6                EBay            12         11.0
7             Netflix            15          9.0
8             Moderna             3         34.0
9         AstraZeneca             5         14.0
10              Apple             4         46.0
11             NASDAQ             1        130.0
12             Garmin            29          6.0

In [15]:
# liczę wartość posiadanych akcji każdej firmy
portfolio['wartosc'] = portfolio['liczba_akcji'] * portfolio['obecny_kurs']
# zsumowana wartość całego portfolio przy obecnym kursie 
portfolio_value = portfolio['wartosc'].sum()
print('portfolio_value', portfolio_value)
# procent wartości akcji w stosunku do wartości całego portfolio
portfolio['procent_wartosci'] = portfolio['wartosc'] / portfolio_value

portfolio_value 1520.0


In [16]:
portfolio

nazwa  liczba_akcji  obecny_kurs  wartosc  procent_wartosci
0               Adobe             2         35.0     70.0          0.046053
1              Makita             3         17.0     51.0          0.033553
2   21 st Century Fox             4         23.0     92.0          0.060526
3           Starbucks             5         12.0     60.0          0.039474
4            Facebook             7         30.0    210.0          0.138158
5          BlackBerry             2         55.0    110.0          0.072368
6                EBay            12         11.0    132.0          0.086842
7             Netflix            15          9.0    135.0          0.088816
8             Moderna             3         34.0    102.0          0.067105
9         AstraZeneca             5         14.0     70.0          0.046053
10              Apple             4         46.0    184.0          0.121053
11             NASDAQ             1        130.0    130.0          0.085526
12             Garmin            29          6.0    174.0          0.114474

In [17]:
wskazniki

sredni_zysk  srednie_odchylenie
0         0.534               5.465
1        -1.749               6.544
2         1.837               7.734
3         0.352               6.283
4         0.163               8.365
5         0.857               4.869
6        -0.874               2.134
7        -0.632               6.674
8         1.375               5.872
9         0.386               3.985
10       -1.474               7.862
11        0.284               4.236
12        1.347               8.357

In [18]:
# łączenie tabeli portfolio z tabelą wskaźniki
portfolio = portfolio.join(wskazniki)
portfolio

nazwa  liczba_akcji  obecny_kurs  wartosc  procent_wartosci  \
0               Adobe             2         35.0     70.0          0.046053   
1              Makita             3         17.0     51.0          0.033553   
2   21 st Century Fox             4         23.0     92.0          0.060526   
3           Starbucks             5         12.0     60.0          0.039474   
4            Facebook             7         30.0    210.0          0.138158   
5          BlackBerry             2         55.0    110.0          0.072368   
6                EBay            12         11.0    132.0          0.086842   
7             Netflix            15          9.0    135.0          0.088816   
8             Moderna             3         34.0    102.0          0.067105   
9         AstraZeneca             5         14.0     70.0          0.046053   
10              Apple             4         46.0    184.0          0.121053   
11             NASDAQ             1        130.0    130.0          0.085526   
12             Garmin            29          6.0    174.0          0.114474   

    sredni_zysk  srednie_odchylenie  
0         0.534               5.465  
1        -1.749               6.544  
2         1.837               7.734  
3         0.352               6.283  
4         0.163               8.365  
5         0.857               4.869  
6        -0.874               2.134  
7        -0.632               6.674  
8         1.375               5.872  
9         0.386               3.985  
10       -1.474               7.862  
11        0.284               4.236  
12        1.347               8.357

In [19]:
# licze sharpe ratio
portfolio['sharpe_ratio'] = portfolio['sredni_zysk'] / portfolio['srednie_odchylenie']
portfolio

nazwa  liczba_akcji  obecny_kurs  wartosc  procent_wartosci  \
0               Adobe             2         35.0     70.0          0.046053   
1              Makita             3         17.0     51.0          0.033553   
2   21 st Century Fox             4         23.0     92.0          0.060526   
3           Starbucks             5         12.0     60.0          0.039474   
4            Facebook             7         30.0    210.0          0.138158   
5          BlackBerry             2         55.0    110.0          0.072368   
6                EBay            12         11.0    132.0          0.086842   
7             Netflix            15          9.0    135.0          0.088816   
8             Moderna             3         34.0    102.0          0.067105   
9         AstraZeneca             5         14.0     70.0          0.046053   
10              Apple             4         46.0    184.0          0.121053   
11             NASDAQ             1        130.0    130.0          0.085526   
12             Garmin            29          6.0    174.0          0.114474   

    sredni_zysk  srednie_odchylenie  sharpe_ratio  
0         0.534               5.465      0.097713  
1        -1.749               6.544     -0.267268  
2         1.837               7.734      0.237523  
3         0.352               6.283      0.056024  
4         0.163               8.365      0.019486  
5         0.857               4.869      0.176012  
6        -0.874               2.134     -0.409560  
7        -0.632               6.674     -0.094696  
8         1.375               5.872      0.234162  
9         0.386               3.985      0.096863  
10       -1.474               7.862     -0.187484  
11        0.284               4.236      0.067044  
12        1.347               8.357      0.161182

In [20]:
# losuję przykładową macierz waiancji-kowariancji
covariance_matrix = 0.008 * np.random.rand(13,13) - 0.003
covariance_matrix

array([[ 2.75763447e-03, -2.35848366e-03,  1.05674694e-03,
         4.58390643e-03,  3.15441208e-03,  2.13602825e-03,
         2.90880002e-04, -1.46493975e-03,  2.88682829e-03,
        -2.48851842e-03,  4.25708682e-03,  4.46953522e-04,
         2.86108953e-04],
       [ 6.75887076e-05,  3.20752213e-03,  3.12736185e-03,
         7.26560590e-04,  4.60262596e-03, -2.90946566e-03,
         4.51062746e-03,  2.96669027e-03,  3.27672891e-03,
         1.48495015e-04,  2.04711038e-03, -2.47378300e-03,
        -1.26528753e-03],
       [ 8.07460208e-04, -8.94925890e-04,  2.28326505e-03,
        -1.67921681e-03,  4.43325526e-03, -2.33497723e-03,
         2.00565682e-03, -2.27441554e-03,  3.85103471e-03,
         1.04813280e-03,  4.03386424e-03,  3.68304827e-03,
         1.77740518e-03],
       [ 1.18961829e-03, -1.27464206e-03,  2.06621746e-03,
         2.28734357e-03, -1.40276536e-03, -1.65411992e-03,
        -2.78051600e-03,  8.94961865e-04, -1.24424634e-05,
        -5.03057160e-04,  4.65619170e

In [21]:
# oczekiwany zwrot z portfolio
portfolio_exp_return = (portfolio['sredni_zysk'] * portfolio['procent_wartosci']).sum()
portfolio_exp_return

0.15359802631578942

In [22]:
# zamieniam pandasową kolumnę na format akceptowany przez numpy
weights = portfolio['procent_wartosci'].to_numpy()

In [31]:
# odchylenie standardowe portfolio
portfolio_std_deviation = np.sqrt(np.matmul(np.matmul(weights, covariance_matrix), weights))
portfolio_std_deviation

0.03254936257913991

In [32]:
# sharpe ratio dla całego portfolio
portfolio_sharpe_ratio = portfolio_exp_return / portfolio_std_deviation
portfolio_sharpe_ratio

4.718925783641202

# Test dla danych (prawie takich samych) jak w filmiku na yt

In [43]:
portfolio = pd.read_csv('film_portfolio.txt')
portfolio

name     mean  std_dev  weights
0  SPY -0.00033  0.05465    0.125
1  MDY  0.00235  0.06544    0.125
2  SLY  0.00228  0.07204    0.125
3  EFA -0.00439  0.06946    0.125
4  EEM  0.00124  0.08707    0.125
5  TLT  0.00818  0.04594    0.125
6  LQD  0.00539  0.02858    0.125
7  GLD  0.01462  0.06016    0.125

In [44]:
# licze sharpe ratio
portfolio['sharpe_ratio'] = portfolio['mean'] / portfolio['std_dev']
portfolio

name     mean  std_dev  weights  sharpe_ratio
0  SPY -0.00033  0.05465    0.125     -0.006038
1  MDY  0.00235  0.06544    0.125      0.035911
2  SLY  0.00228  0.07204    0.125      0.031649
3  EFA -0.00439  0.06946    0.125     -0.063202
4  EEM  0.00124  0.08707    0.125      0.014241
5  TLT  0.00818  0.04594    0.125      0.178058
6  LQD  0.00539  0.02858    0.125      0.188593
7  GLD  0.01462  0.06016    0.125      0.243019

In [40]:
covariance_matrix = pd.read_csv('film_kowariancja.txt', names=['SPY','MDY','SLY','EFA','EEM','TLT','LQD','GLD'])
covariance_matrix

SPY       MDY       SLY       EFA       EEM       TLT       LQD  \
0  0.002987  0.003433  0.003759  0.003552  0.004195 -0.000690  0.000566   
1  0.003433  0.004282  0.004645  0.004051  0.005018 -0.000980  0.000624   
2  0.003759  0.004645  0.005190  0.004387  0.005371 -0.001040  0.000662   
3  0.003552  0.004051  0.004387  0.004824  0.005585 -0.000570  0.000899   
4  0.004195  0.005018  0.005371  0.005585  0.007582 -0.001080  0.000921   
5 -0.000690 -0.000980 -0.001040 -0.000570 -0.001080  0.002111  0.000516   
6  0.000566  0.000624  0.000662  0.000899  0.000921  0.000516  0.000817   
7  0.000345  0.000498  0.000352  0.000767  0.001528  0.000425  0.000291   

        GLD  
0  0.000345  
1  0.000498  
2  0.000352  
3  0.000767  
4  0.001528  
5  0.000425  
6  0.000291  
7  0.003619

In [41]:
covariance_matrix = covariance_matrix.to_numpy()
covariance_matrix

array([[ 0.002987,  0.003433,  0.003759,  0.003552,  0.004195, -0.00069 ,
         0.000566,  0.000345],
       [ 0.003433,  0.004282,  0.004645,  0.004051,  0.005018, -0.00098 ,
         0.000624,  0.000498],
       [ 0.003759,  0.004645,  0.00519 ,  0.004387,  0.005371, -0.00104 ,
         0.000662,  0.000352],
       [ 0.003552,  0.004051,  0.004387,  0.004824,  0.005585, -0.00057 ,
         0.000899,  0.000767],
       [ 0.004195,  0.005018,  0.005371,  0.005585,  0.007582, -0.00108 ,
         0.000921,  0.001528],
       [-0.00069 , -0.00098 , -0.00104 , -0.00057 , -0.00108 ,  0.002111,
         0.000516,  0.000425],
       [ 0.000566,  0.000624,  0.000662,  0.000899,  0.000921,  0.000516,
         0.000817,  0.000291],
       [ 0.000345,  0.000498,  0.000352,  0.000767,  0.001528,  0.000425,
         0.000291,  0.003619]])

In [47]:
# oczekiwany zwrot z portfolio
portfolio_exp_return = np.matmul(portfolio['mean'], portfolio['weights'])
portfolio_exp_return

0.0036674999999999998

In [50]:
# zamieniam pandasową kolumnę na format akceptowany przez numpy
weights = portfolio['weights'].to_numpy()
weights

array([0.125, 0.125, 0.125, 0.125, 0.125, 0.125, 0.125, 0.125])

In [51]:
# odchylenie standardowe portfolio
portfolio_std_deviation = np.sqrt(np.matmul(np.matmul(weights, covariance_matrix), weights))
portfolio_std_deviation

0.04462902642899574

In [52]:
# sharpe ratio dla całego portfolio
portfolio_sharpe_ratio = portfolio_exp_return / portfolio_std_deviation
portfolio_sharpe_ratio

0.08217745923350915

### okej, wszystko do tego momentu śmiga jak trzeba

In [57]:
import scipy.optimize as opt

In [59]:
# funkcja która liczy na raz odchylenie standardowe portfolio w zależności od wag
# covariance_matrix musi być zmienną globalną
def get_portfolio_std_deviation(weights):
    portfolio_std_deviation = np.sqrt(np.matmul(np.matmul(weights, covariance_matrix), weights))
    return portfolio_std_deviation

In [60]:
opt.minimize(get_portfolio_std_deviation, weights)

      fun: 9.133476161451092e-10
 hess_inv: array([[ 2.37884615e-05, -1.02807366e-05,  2.83120995e-06,
        -1.41159578e-05,  3.87700450e-07, -5.29192798e-06,
         5.80067585e-06, -1.57729386e-07],
       [-1.02807366e-05,  3.63847307e-05, -3.08912137e-05,
         6.47804661e-07,  3.58571621e-06,  5.41445651e-06,
         4.63702653e-07, -2.23896649e-06],
       [ 2.83120995e-06, -3.08912137e-05,  3.30278296e-05,
        -9.44326231e-07, -4.90014470e-06, -5.40160783e-06,
         1.34908613e-08,  3.78345411e-06],
       [-1.41159578e-05,  6.47804661e-07, -9.44326231e-07,
         2.33484315e-05, -6.75126480e-06,  3.36842054e-06,
        -1.08296126e-05, -1.12578306e-06],
       [ 3.87700450e-07,  3.58571621e-06, -4.90014470e-06,
        -6.75126480e-06,  6.54784465e-06,  2.54932777e-06,
         1.39795049e-06, -8.25317140e-07],
       [-5.29192798e-06,  5.41445651e-06, -5.40160783e-06,
         3.36842054e-06,  2.54932777e-06,  5.06419076e-06,
        -5.02043302e-06, -9.88189

In [ ]:
x: array([ 4.21137175e-08,  3.81416142e-08, -6.09196625e-08, -1.64772788e-08,
        3.81600104e-09, -3.40833440e-09, -2.47293112e-09, -3.98158601e-09])